# NumPy Test 2

In [1]:
import numpy as np

## 1. Create an array and find sum of it


In [2]:
a = np.random.randint(30,size=(5,3))
np.sum(a)

243

## 2. Find sin of given array.

In [3]:
a = np.array([[2,3,4],[5,6,7]])
np.sin(a)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

## 3. Find mean of matrix along row and column.

In [4]:
a = np.random.randint(10,size=(3,3))
print(a)
print('Row',a.mean(axis=0))
print('Column',a.mean(axis=1))

[[2 1 6]
 [8 1 1]
 [3 5 2]]
Row [4.33333333 2.33333333 3.        ]
Column [3.         3.33333333 3.33333333]


## 4. Find standard deviation of given array.


In [5]:
print(a.std(axis=0))
print(a.std(axis=1))

[2.62466929 1.88561808 2.1602469 ]
[2.1602469  3.29983165 1.24721913]


## 5. Create a 3*3 matrix and print it's transpose matrix


In [6]:
a = np.random.randint(10,size=(3,3))
print(a)
print('matrix after transpose')
a.T

[[0 6 7]
 [4 6 1]
 [8 0 5]]
matrix after transpose


array([[0, 4, 8],
       [6, 6, 0],
       [7, 1, 5]])

## 6. Create an array of 3*3 and find index of max along both axis.

In [7]:
a = np.random.randint(10,size=(3,3))
print(a)
print(a.argmax(axis=0))
print(a.argmax(axis=1))

[[4 0 8]
 [5 5 0]
 [4 9 0]]
[1 2 0]
[2 0 1]


## 7.  find sum of two matrix

In [8]:
a = np.array([[2,3,5],[5,8,21]])
print(a)
v = [1,2,3]
a+v

[[ 2  3  5]
 [ 5  8 21]]


array([[ 3,  5,  8],
       [ 6, 10, 24]])

## 8. Find indexes of max element along axis=0 and axis=1

In [9]:
a = np.array([[2,12,5],[5,8,21]])
print(a.max(axis=0))
print(a.max(axis=1))

[ 5 12 21]
[12 21]


## 9. Write a program to add two arrays of different shape.
Hint: Broadcasting
sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[  1.,   2.,   3.],

 [ 11.,  12.,  13.],
 
 [ 21.,  22.,  23.],
 
 [ 31.,  32.,  33.]]

In [10]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis]+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

## 10. Try to solve a array and print a array with indices which would sort the given array.

sample input:

a = [3,1,8,2]

output:

[1,3,0,2]

In [11]:
x = np.array([3,1,8,2])
x1 = np.argsort(x)
print(x1)

[1 3 0 2]


## 11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis

In [12]:
x = np.random.randint(10,50,(3,3))
print("along axis 1:\n",np.argsort(x, axis=1))
print("along axis 0:\n",np.argsort(x, axis=0))

along axis 1:
 [[2 0 1]
 [0 2 1]
 [2 0 1]]
along axis 0:
 [[1 1 0]
 [0 0 1]
 [2 2 2]]


## 12. calculate multiplication of transpose and matrix itself of a 3*3 matrix

In [13]:
a = np.random.randint(10,size=(3,3)) 
print("original matrix:\n",a) 
print("Transpose of a:\n",a.T) 
print("Multiplication:\n",a*a.T)

original matrix:
 [[7 6 2]
 [9 7 3]
 [9 3 2]]
Transpose of a:
 [[7 9 9]
 [6 7 3]
 [2 3 2]]
Multiplication:
 [[49 54 18]
 [54 49  9]
 [18  9  4]]


## 13. Find solution for given linear equstion:

2x + 5*y = 28
4*x + 3*y = 81

In [14]:
a = np.array([[2, 5], [4, 3]])  
b = np.array([28, 81]) 
print("Solution is:", np.linalg.solve(a, b))

Solution is: [22.92857143 -3.57142857]


## 14. Find Rank, Trace, Inverse, Determinant of a given matrix

A=[[1, 1, 1], 
  [2, 2, 2], 
  [3, 3, 3]])

In [15]:
A = [[1, 4, 6], [9, 2, 8], [7, 3, 5]]
print("Rank:\n", np.linalg.matrix_rank(A)) 
  
print("Trace:\n", np.trace(A)) 
  
print("Determinant:\n", np.linalg.det(A)) 
  
print("Inverse:\n", np.linalg.inv(A)) 
  

Rank:
 3
Trace:
 8
Determinant:
 108.00000000000003
Inverse:
 [[-0.12962963 -0.01851852  0.18518519]
 [ 0.10185185 -0.34259259  0.42592593]
 [ 0.12037037  0.23148148 -0.31481481]]


## 15. Find cube of a mtrix

In [16]:
A = [[1, 4, 6], [9, 2, 8], [7, 3, 5]]

np.linalg.matrix_power(A, 3)

array([[ 825,  580, 1054],
       [1429,  790, 1560],
       [1147,  647, 1261]])