# NumPy Test 1

In [1]:
import numpy as np

## 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [2]:
np.random.seed(1)
a = np.random.randint(5,size=[3,3])
print('Array created is : ',a)
elements, counts = np.unique(a,return_counts=True)
print('Unique elements in array are : ',elements)
print('frequencies of each element is : ',counts)

Array created is :  [[3 4 0]
 [1 3 0]
 [0 1 4]]
Unique elements in array are :  [0 1 3 4]
frequencies of each element is :  [3 2 2 2]


## 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function

In [3]:
given_integer =np.arange(9).reshape((3,3))
given_integer

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 3. How to find the memory size of any array

In [4]:
array = np.arange(9).reshape((3,3))
print("Memory size of a NumPy array: ",array.nbytes)

Memory size of a NumPy array:  36


## 4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside

In [5]:
array = np.ones((10,10))
array[1:-1,1:-1]  = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 5.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
checkboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 6. Normalize a 5x5 random matrix
normalization formula : ((a-mean(a))/std(a))

In [7]:
np.random.seed(1)
a= np.random.randint(50, size = (5,5))
print('Original Matrix')
print(a)
print('Matrix after Normalization')
a = (a-a.mean())/np.std(a)
print(a)

Original Matrix
[[37 43 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 45  6]
 [25 20 37 18 20]
 [11 42 28 29 14]]
Matrix after Normalization
[[ 1.37839284  1.83380897 -0.51917439 -0.82278515 -0.74688246]
 [-0.59507708 -1.05049322 -0.29146633 -1.43000667 -0.21556364]
 [-1.35410398 -0.51917439 -0.89868784  1.98561435 -0.97459053]
 [ 0.46756057  0.08804712  1.37839284 -0.06375826  0.08804712]
 [-0.59507708  1.75790628  0.69526863  0.77117132 -0.36736902]]


## 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place

In [8]:
negate = np.arange(11)
negate[(3 < negate) & (negate < 8)] *= -1
print(negate)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 8. How to get the dates of yesterday, today and tomorrow?

In [9]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-11-08
Today:  2020-11-09
Tomorrow:  2020-11-10


## 9. Generate two arrays of size 2X4 & 3X3, find difference between them

In [16]:
np.random.seed(1)
array1 = np.random.randint(10, size = (2,4))
array2 = np.random.randint(10, size = (3,3))
subtract = np.subtract(array1,array2)

ValueError: operands could not be broadcast together with shapes (2,4) (3,3) 

## 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [10]:
array1 = np.array(['cat', 'dog', 'rat'])

array2 = np.random.choice(array1, size=100)

print('Generated 100 elements are', array2, sep='\n')

Generated 100 elements are
['rat' 'cat' 'dog' 'dog' 'rat' 'cat' 'rat' 'dog' 'dog' 'dog' 'dog' 'rat'
 'dog' 'dog' 'cat' 'cat' 'dog' 'cat' 'cat' 'dog' 'rat' 'dog' 'cat' 'rat'
 'rat' 'dog' 'dog' 'dog' 'cat' 'cat' 'dog' 'cat' 'rat' 'cat' 'cat' 'dog'
 'dog' 'rat' 'cat' 'cat' 'dog' 'rat' 'rat' 'dog' 'cat' 'rat' 'dog' 'rat'
 'dog' 'cat' 'dog' 'dog' 'rat' 'cat' 'cat' 'rat' 'rat' 'dog' 'cat' 'rat'
 'rat' 'rat' 'cat' 'cat' 'dog' 'dog' 'dog' 'cat' 'cat' 'dog' 'dog' 'rat'
 'cat' 'dog' 'rat' 'rat' 'cat' 'dog' 'dog' 'cat' 'cat' 'cat' 'rat' 'cat'
 'dog' 'cat' 'dog' 'cat' 'cat' 'rat' 'cat' 'dog' 'rat' 'cat' 'dog' 'dog'
 'cat' 'rat' 'cat' 'cat']


## 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [11]:
array = np.random.uniform(low=0, high=1, size=10)
print(array)

[0.35653172 0.75278835 0.88134183 0.01166919 0.49810907 0.07379201
 0.78695147 0.06406733 0.35531036 0.94183695]


## 12. Given a two dimensional array, how to extract unique rows?

In [12]:
matrix = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 0]])

print('Unique rows are', np.unique(matrix, axis=0), sep='\n')

Unique rows are
[[0 0 0]
 [0 0 1]]


## 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

## 14. How to find the closest value (to a given scalar) in a vector?

In [14]:
array = np.array([1, 2, 3, 4, 5])

k = 4.01 
closest_value = array[np.abs(array - k).argmin()]

print('Closest value to {} is {}'.format(k, closest_value))

Closest value to 4.01 is 4


## 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance

In [15]:
vect = np.random.randn(10, 2)

x,y = np.atleast_2d(vect[:,0], vect[:,1])
dist = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print('Distance between all pais are', dist, sep='\n')

Distance between all pais are
[[0.         2.65085592 2.17298218 1.62401607 2.93260332 2.67713553
  0.59602301 2.21509816 0.54124571 1.68532143]
 [2.65085592 0.         0.60936404 1.15783135 0.95533178 0.78296536
  2.15194026 0.92604782 2.70837898 2.45939872]
 [2.17298218 0.60936404 0.         0.58070685 1.43396003 1.19381476
  1.62775878 0.39905527 2.32306329 1.85223264]
 [1.62401607 1.15783135 0.58070685 0.         1.81909065 1.55135988
  1.05813723 0.61036812 1.84090234 1.39667882]
 [2.93260332 0.95533178 1.43396003 1.81909065 0.         0.27271636
  2.57486303 1.81793429 2.80782277 3.21381909]
 [2.67713553 0.78296536 1.19381476 1.55135988 0.27271636 0.
  2.3063971  1.5861203  2.57542182 2.94746916]
 [0.59602301 2.15194026 1.62775878 1.05813723 2.57486303 2.3063971
  0.         1.63152476 0.98411141 1.24689842]
 [2.21509816 0.92604782 0.39905527 0.61036812 1.81793429 1.5861203
  1.63152476 0.         2.45125753 1.57919038]
 [0.54124571 2.70837898 2.32306329 1.84090234 2.80782277 2.5

## 16. How to sort an array by the nth column?

In [16]:
np.random.seed(1)
sortarr = np.random.randint(0,10,(3,3))
print(sortarr)
print('Sorted array is: ')
print(sortarr[sortarr[:,1].argsort()])

[[5 8 9]
 [5 0 0]
 [1 7 6]]
Sorted array is: 
[[5 0 0]
 [1 7 6]
 [5 8 9]]


## 17.How to tell if a given 2D array has null columns?

In [17]:
np.random.seed(1)
nullcol = np.random.randint(0,3,(3,10))
print(nullcol)
print((~nullcol.any(axis=0)).any())

[[1 0 0 1 1 0 0 1 0 1]
 [0 2 1 2 0 2 1 2 0 0]
 [2 0 1 2 2 0 1 1 2 0]]
False


## 18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [18]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Array is', array, sep='\n')

print('Sum of last two columns are', np.sum(array[:, -2:]))

Array is
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of last two columns are 33


## 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [ ]:
array = np.random.rand(5, 5)
print('Original array', array, sep='\n')

for i in range(5):
    array[:, i] += (i+1)
    
print('Modified array', array, sep='\n')

## 20. Given a 1d array(size 100) of boolean values, identify total number of True in it

## 21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [24]:
vec = np.array([1, 2, 3, 4, 5])

num_zero = 12 

new_arr = np.zeros(17)
new_arr[::4] = vec

print('New array is', new_arr, sep='\n')

New array is
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 22. How to swap two rows of an array?

In [23]:
array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print('Original array is', array, sep='\n')
array[[0, 1]] = array[[1, 0]]
print('Modified array is', array, sep='\n')

Original array is
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Modified array is
[[3 4 5]
 [0 1 2]
 [6 7 8]]


## 23. How to get n largest value of an array?

In [21]:
array = np.array([0, 1, 5, 2, 4, 6, 7, 8, 9])
n = 4
array.sort()
print('{} largest values are {}'.format(n, array[-n:]))
print('{}th largest value is {}'.format(n, array[-n]))

4 largest values are [6 7 8 9]
4th largest value is 6


## 24. Given two random arrays of shape 5X5, identify the common elements between them

In [20]:
array1 = np.random.randint(1, 5, size=25).reshape((5, 5))
array2 = np.random.randint(1, 5, size=25).reshape((5, 5))

print('array1', array1, sep='\n')
print('array2', array2, sep='\n')
print('Common elements between arrays are', np.intersect1d(array1, array2))

array1
[[3 2 2 2 4]
 [4 2 3 2 2]
 [1 1 2 1 1]
 [2 4 4 3 2]
 [1 3 4 4 3]]
array2
[[2 2 2 4 1]
 [1 2 4 1 3]
 [1 1 2 4 2]
 [3 4 1 1 2]
 [4 3 4 4 3]]
Common elements between arrays are [1 2 3 4]


## 25. How to get index of top two highest value in a 1d array?
[2,22,11,-11,33,7,13,872,-23]

In [19]:
array = np.array([2,22,11,-11,33,7,13,872,-23])
print( array)
print('Index of two highest values are', array.argsort()[-2:][::-1])

[  2  22  11 -11  33   7  13 872 -23]
Index of two highest values are [7 4]
